namespace ReSys.Core.Domain.Promotions.Actions;

/// <summary>
/// Configures the database mapping for the <see cref="PromotionAction"/> entity.
/// </summary>
public sealed class PromotionActionConfiguration : IEntityTypeConfiguration<PromotionAction>
{
    /// <summary>
    /// Configures the entity of type <see cref="PromotionAction"/>.
    /// </summary>
    /// <param name="builder">The builder to be used to configure the entity type.</param>
    public void Configure(EntityTypeBuilder<PromotionAction> builder)
    {
        #region Table
        // Set the table name for the PromotionUsage entity to its own table.
        builder.ToTable(name: Schema.PromotionUsages);
        #endregion

        #region Primary Key
        // Configure the primary key for the PromotionUsage entity.
        builder.HasKey(keyExpression: pu => pu.Id);
        #endregion

        #region Properties
        // Configure individual properties of the PromotionUsage entity.
        builder.Property(propertyExpression: pu => pu.Id)
            .ValueGeneratedNever() // Assuming Id is generated by domain logic (Guid.NewGuid())
            .HasComment(comment: "Id: Unique identifier for the promotion usage action.");

        builder.Property(propertyExpression: pu => pu.PromotionId)
            .IsRequired()
            .HasComment(comment: "PromotionId: Foreign key to the associated Promotion.");

        builder.Property(propertyExpression: pu => pu.Type)
            .HasConversion<string>() // Store enum as string
            .HasMaxLength(maxLength: 50) // Max length for enum string representation
            .IsRequired()
            .HasComment(comment: "Type: The type of promotion action (e.g., OrderDiscount, ItemDiscount).");

        // Apply common configurations using extension methods.
        builder.ConfigureMetadata(); // For IHasMetadata
        builder.ConfigureAuditable(); // For AuditableEntity
        #endregion

        #region Relationships
        // A PromotionUsage belongs to one Promotion.
        // The HasForeignKey is already defined on the PromotionUsage side (PromotionId).
        // WithOne configuration for the inverse navigation from Promotion.
        // This is a one-to-one relationship using a shared primary key (PromotionId also acts as PK for PromotionUsage).
        // EF Core will automatically detect that PromotionUsage.Id is the PK, and PromotionUsage.PromotionId is the FK.
        // We do not want shared primary key, we want PromotionUsage to have its own PK (Id) and PromotionId to be its FK.
        // The one-to-one relationship from Promotion.Action to PromotionUsage should look like this:
        builder.HasOne(navigationExpression: pu => pu.Promotion)
            .WithOne(navigationExpression: p => p.Action)
            .HasForeignKey<PromotionAction>(foreignKeyExpression: pu => pu.PromotionId)
            .IsRequired()
            .OnDelete(deleteBehavior: DeleteBehavior.Cascade);
        #endregion
    }
}